### ISSUE TITLE
Please add me to your website - thank you.

### ISSUE THREAD

**Issue by acctimize** [longitude-digital/Ulink#29]
{
  "user": "acctimize",
  "profile": "https://acctimize.com/",
  "symbol": "@acctimize",
  "name": "Acctimize",
  "photo": "https://res.cloudinary.com/analogyofpearl/image/upload/v1676034585/Acctimize/images/logo_acctimize_graphic_only.png",
  "display":"acctimize",

  "body":[
    {"id":"1","Acctimize.com":"Link_1","url":"https://acctimize.com/"}
  ]
}

**Comment by Benjamin-del** [comment]
This project has to be forked to work. I don't have any options for any hosting services for this project (yet). Unfortunately this is a demo and I don't take requests to change that part of the project. 

Looking at your setup, the symbol should be just `@`. The symbol is just of you would like to remove it or use something different


Feel free to fork it and host it, If you need more help: https://github.com/Benja-media/Ulink#geting-started
